### ISSUE TITLE
Error: Cannot find module 'eslint-config-ember'

### ISSUE THREAD

**Issue by roosnic1** [jonathanKingston/ember-cli-eslint#24]
I have a standard ember-cli app and installed ember-cli-eslint with ``` ember install ember-cli-eslint```. My .eslintrc contains the following:

```json
{
    "parser": "babel-eslint",
    "extends": "ember"
}
```
But when I run ```eslint app/adapters/application.js``` I get the following error:

```sh
/Users/nicolas/.nvm/versions/node/v4.0.0/lib/node_modules/eslint/lib/config.js:209
                    throw e;
                    ^

Error: Cannot find module 'eslint-config-ember'
Referenced from: /Users/nicolas/development/dkz_website/.eslintrc
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at readConfigFromFile (/Users/nicolas/.nvm/versions/node/v4.0.0/lib/node_modules/eslint/lib/config.js:151:44)
    at loadConfig (/Users/nicolas/.nvm/versions/node/v4.0.0/lib/node_modules/eslint/lib/config.js:172:22)
    at /Users/nicolas/.nvm/versions/node/v4.0.0/lib/node_modules/eslint/lib/config.js:203:46
    at Array.reduceRight (native)
    at loadConfig (/Users/nicolas/.nvm/versions/node/v4.0.0/lib/node_modules/eslint/lib/config.js:187:36)
    at getLocalConfig (/Users/nicolas/.nvm/versions/node/v4.0.0/lib/node_modules/eslint/lib/config.js:317:23)
```
I'm using the following versions:
ember-cli: 1.13.8
ember-cli-eslint: 1.2.1
node: 4.0.0
npm: 2.13.4
os: darwin x64

Thanks for your help.

**Comment by kevintechie** [comment]
This is happening because you're executing the global eslint, but the eslint-config-ember module is installed locally to the project.

You need to install eslint locally to the project and execute the local version. For example:

`$ node_modules/.bin/eslint app/app.js`

**Comment by roosnic1** [comment]
Thank you for your answer. With your command i could execute eslint from the command line.

**Comment by jonathanKingston** [comment]
@roosnic1 and @kevintechie - installing the ember config globally should also fix this:
```
npm install -g eslint-config-ember
```

**Comment by roosnic1** [comment]
@jonathanKingston  Thanks for the tip. That way the linter in sublimeText works as well. :+1:
